blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Discussions
    url: https://github.com/Kenneth-Sangli/Vyzio_website/discussions
    about: Posez des questions et discutez avec la communautÃ©
  - name: ğŸ“– Documentation
    url: https://github.com/Kenneth-Sangli/Vyzio_website/wiki
    about: Consultez notre documentation
